"use client";

import { useCallback, useRef } from "react";
import type { CountryFeature } from "@/types/country";

const NAMES: Record<string, [string, string]> = {
  "004": ["Afghanistan", "South Asia"], "008": ["Albania", "Southern Europe"],
  "010": ["Antarctica", "Antarctica"], "012": ["Algeria", "North Africa"],
  "016": ["American Samoa", "Oceania"], "020": ["Andorra", "Southern Europe"],
  "024": ["Angola", "Central Africa"], "028": ["Antigua and Barbuda", "Caribbean"],
  "031": ["Azerbaijan", "Western Asia"], "032": ["Argentina", "South America"],
  "036": ["Australia", "Oceania"], "040": ["Austria", "Western Europe"],
  "044": ["Bahamas", "Caribbean"], "048": ["Bahrain", "Western Asia"],
  "050": ["Bangladesh", "South Asia"], "051": ["Armenia", "Western Asia"],
  "052": ["Barbados", "Caribbean"], "056": ["Belgium", "Western Europe"],
  "060": ["Bermuda", "North America"], "064": ["Bhutan", "South Asia"],
  "068": ["Bolivia", "South America"], "070": ["Bosnia and Herzegovina", "Southern Europe"],
  "072": ["Botswana", "Southern Africa"], "074": ["Bouvet Island", "Antarctica"],
  "076": ["Brazil", "South America"], "084": ["Belize", "Central America"],
  "090": ["Solomon Islands", "Oceania"], "092": ["British Virgin Islands", "Caribbean"],
  "096": ["Brunei", "Southeast Asia"], "100": ["Bulgaria", "Eastern Europe"],
  "104": ["Myanmar", "Southeast Asia"], "108": ["Burundi", "East Africa"],
  "112": ["Belarus", "Eastern Europe"], "116": ["Cambodia", "Southeast Asia"],
  "120": ["Cameroon", "Central Africa"], "124": ["Canada", "North America"],
  "132": ["Cape Verde", "West Africa"], "140": ["Central African Republic", "Central Africa"],
  "144": ["Sri Lanka", "South Asia"], "148": ["Chad", "Central Africa"],
  "152": ["Chile", "South America"], "156": ["China", "East Asia"],
  "158": ["Taiwan", "East Asia"], "162": ["Christmas Island", "Oceania"],
  "166": ["Cocos Islands", "Oceania"], "170": ["Colombia", "South America"],
  "174": ["Comoros", "East Africa"], "178": ["Congo", "Central Africa"],
  "180": ["Dem. Rep. Congo", "Central Africa"], "184": ["Cook Islands", "Oceania"],
  "188": ["Costa Rica", "Central America"], "191": ["Croatia", "Southern Europe"],
  "192": ["Cuba", "Caribbean"], "196": ["Cyprus", "Western Asia"],
  "203": ["Czechia", "Eastern Europe"], "204": ["Benin", "West Africa"],
  "208": ["Denmark", "Northern Europe"], "212": ["Dominica", "Caribbean"],
  "214": ["Dominican Republic", "Caribbean"], "218": ["Ecuador", "South America"],
  "222": ["El Salvador", "Central America"], "226": ["Equatorial Guinea", "Central Africa"],
  "231": ["Ethiopia", "East Africa"], "232": ["Eritrea", "East Africa"],
  "233": ["Estonia", "Northern Europe"], "234": ["Faroe Islands", "Northern Europe"],
  "239": ["South Georgia", "Antarctica"], "242": ["Fiji", "Oceania"],
  "246": ["Finland", "Northern Europe"], "250": ["France", "Western Europe"],
  "258": ["French Polynesia", "Oceania"], "260": ["French Southern Territories", "Antarctica"],
  "262": ["Djibouti", "East Africa"], "266": ["Gabon", "Central Africa"],
  "268": ["Georgia", "Western Asia"], "270": ["Gambia", "West Africa"],
  "275": ["Palestine", "Western Asia"], "276": ["Germany", "Western Europe"],
  "288": ["Ghana", "West Africa"], "296": ["Kiribati", "Oceania"],
  "300": ["Greece", "Southern Europe"], "304": ["Greenland", "North America"],
  "308": ["Grenada", "Caribbean"], "320": ["Guatemala", "Central America"],
  "324": ["Guinea", "West Africa"], "328": ["Guyana", "South America"],
  "332": ["Haiti", "Caribbean"], "334": ["Heard Island", "Antarctica"],
  "340": ["Honduras", "Central America"], "344": ["Hong Kong", "East Asia"],
  "348": ["Hungary", "Eastern Europe"], "352": ["Iceland", "Northern Europe"],
  "356": ["India", "South Asia"], "360": ["Indonesia", "Southeast Asia"],
  "364": ["Iran", "Western Asia"], "368": ["Iraq", "Western Asia"],
  "372": ["Ireland", "Northern Europe"], "376": ["Israel", "Western Asia"],
  "380": ["Italy", "Southern Europe"], "384": ["Ivory Coast", "West Africa"],
  "388": ["Jamaica", "Caribbean"], "392": ["Japan", "East Asia"],
  "398": ["Kazakhstan", "Central Asia"], "400": ["Jordan", "Western Asia"],
  "404": ["Kenya", "East Africa"], "408": ["North Korea", "East Asia"],
  "410": ["South Korea", "East Asia"], "414": ["Kuwait", "Western Asia"],
  "417": ["Kyrgyzstan", "Central Asia"], "418": ["Laos", "Southeast Asia"],
  "422": ["Lebanon", "Western Asia"], "426": ["Lesotho", "Southern Africa"],
  "428": ["Latvia", "Northern Europe"], "430": ["Liberia", "West Africa"],
  "434": ["Libya", "North Africa"], "438": ["Liechtenstein", "Western Europe"],
  "440": ["Lithuania", "Northern Europe"], "442": ["Luxembourg", "Western Europe"],
  "450": ["Madagascar", "East Africa"], "454": ["Malawi", "East Africa"],
  "458": ["Malaysia", "Southeast Asia"], "462": ["Maldives", "South Asia"],
  "466": ["Mali", "West Africa"], "469": ["Mayotte", "East Africa"],
  "470": ["Malta", "Southern Europe"], "478": ["Mauritania", "West Africa"],
  "480": ["Mauritius", "East Africa"], "484": ["Mexico", "North America"],
  "496": ["Mongolia", "East Asia"], "498": ["Moldova", "Eastern Europe"],
  "499": ["Montenegro", "Southern Europe"], "504": ["Morocco", "North Africa"],
  "508": ["Mozambique", "East Africa"], "512": ["Oman", "Western Asia"],
  "516": ["Namibia", "Southern Africa"], "520": ["Nauru", "Oceania"],
  "524": ["Nepal", "South Asia"], "528": ["Netherlands", "Western Europe"],
  "540": ["New Caledonia", "Oceania"], "544": ["Niue", "Oceania"],
  "548": ["Vanuatu", "Oceania"], "554": ["New Zealand", "Oceania"],
  "558": ["Nicaragua", "Central America"], "562": ["Niger", "West Africa"],
  "566": ["Nigeria", "West Africa"], "578": ["Norway", "Northern Europe"],
  "580": ["Northern Mariana Islands", "Oceania"], "583": ["Micronesia", "Oceania"],
  "585": ["Palau", "Oceania"], "586": ["Pakistan", "South Asia"],
  "591": ["Panama", "Central America"], "598": ["Papua New Guinea", "Oceania"],
  "600": ["Paraguay", "South America"], "604": ["Peru", "South America"],
  "608": ["Philippines", "Southeast Asia"], "612": ["Pitcairn Islands", "Oceania"],
  "616": ["Poland", "Eastern Europe"], "620": ["Portugal", "Southern Europe"],
  "624": ["Guinea-Bissau", "West Africa"], "626": ["Timor-Leste", "Southeast Asia"],
  "630": ["Puerto Rico", "Caribbean"], "634": ["Qatar", "Western Asia"],
  "642": ["Romania", "Eastern Europe"], "643": ["Russia", "Eastern Europe"],
  "646": ["Rwanda", "East Africa"], "654": ["St. Helena", "West Africa"],
  "659": ["Saint Kitts and Nevis", "Caribbean"], "660": ["Anguilla", "Caribbean"],
  "662": ["Saint Lucia", "Caribbean"], "666": ["St. Pierre and Miquelon", "North America"],
  "670": ["Saint Vincent and the Grenadines", "Caribbean"], "674": ["San Marino", "Southern Europe"],
  "678": ["Sao Tome and Principe", "Central Africa"], "682": ["Saudi Arabia", "Western Asia"],
  "686": ["Senegal", "West Africa"], "688": ["Serbia", "Southern Europe"],
  "690": ["Seychelles", "East Africa"], "694": ["Sierra Leone", "West Africa"],
  "698": ["Sint Maarten", "Caribbean"], "702": ["Singapore", "Southeast Asia"],
  "703": ["Slovakia", "Eastern Europe"], "704": ["Vietnam", "Southeast Asia"],
  "705": ["Slovenia", "Southern Europe"], "706": ["Somalia", "East Africa"],
  "710": ["South Africa", "Southern Africa"], "716": ["Zimbabwe", "East Africa"],
  "724": ["Spain", "Southern Europe"], "728": ["South Sudan", "East Africa"],
  "729": ["Sudan", "North Africa"], "732": ["Western Sahara", "North Africa"],
  "733": ["Falkland Islands", "South America"], "740": ["Suriname", "South America"],
  "748": ["Eswatini", "Southern Africa"], "752": ["Sweden", "Northern Europe"],
  "756": ["Switzerland", "Western Europe"], "760": ["Syria", "Western Asia"],
  "762": ["Tajikistan", "Central Asia"], "764": ["Thailand", "Southeast Asia"],
  "768": ["Togo", "West Africa"], "772": ["Tokelau", "Oceania"],
  "776": ["Tonga", "Oceania"], "780": ["Trinidad and Tobago", "Caribbean"],
  "784": ["United Arab Emirates", "Western Asia"], "788": ["Tunisia", "North Africa"],
  "792": ["Turkey", "Western Asia"], "795": ["Turkmenistan", "Central Asia"],
  "796": ["Turks and Caicos", "Caribbean"], "798": ["Tuvalu", "Oceania"],
  "800": ["Uganda", "East Africa"], "804": ["Ukraine", "Eastern Europe"],
  "807": ["North Macedonia", "Southern Europe"], "818": ["Egypt", "North Africa"],
  "826": ["United Kingdom", "Northern Europe"], "831": ["Guernsey", "Northern Europe"],
  "832": ["Jersey", "Northern Europe"], "833": ["Isle of Man", "Northern Europe"],
  "834": ["Tanzania", "East Africa"], "840": ["United States", "North America"],
  "854": ["Burkina Faso", "West Africa"], "858": ["Uruguay", "South America"],
  "860": ["Uzbekistan", "Central Asia"], "862": ["Venezuela", "South America"],
  "876": ["Wallis and Futuna", "Oceania"], "882": ["Samoa", "Oceania"],
  "887": ["Yemen", "Western Asia"], "894": ["Zambia", "East Africa"],
  "-99": ["N. Cyprus", "Western Asia"],
};

export function resolveCountry(geoId: string): CountryFeature | null {
  const entry = NAMES[geoId];
  if (!entry) return null;
  return {
    id: geoId,
    name: entry[0],
    region: entry[1],
    polygons: [],
  };
}

export function useWorldMap() {
  const mousePos = useRef<{ x: number; y: number } | null>(null);

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    mousePos.current = { x: e.clientX, y: e.clientY };
  }, []);

  return { mousePos, handleMouseMove };
}
