export interface DestinationItem {
  id: string;
  slug: string;
  name: string;
  category: "india" | "international" | "popular";
  subCategory?: string;
  image: string;
  description: string;
  region: string;
  rating: number;
  reviewsCount: number;
  bestTime: string;
  topAttractions: string[];
  vibe: string;
  featured?: boolean;
}

export const DESTINATIONS_DATA: DestinationItem[] = [
  // ── IN INDIA ──────────────────────────────────────
  {
    id: "north-india",
    slug: "north-india",
    name: "North India",
    category: "india",
    subCategory: "Region",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    description: "Snow-capped Himalayas, historic monuments, spiritual ghats, and royal palaces.",
    region: "India",
    rating: 4.8,
    reviewsCount: 1240,
    bestTime: "Oct - Mar",
    topAttractions: ["Taj Mahal", "Varanasi Ghats", "Leh-Ladakh", "Golden Temple"],
    vibe: "Historical & Majestic",
    featured: true
  },
  {
    id: "south-india",
    slug: "south-india",
    name: "South India",
    category: "india",
    subCategory: "Region",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    description: "Serene backwaters, ancient Dravidian temples, lush tea gardens, and coastal beauty.",
    region: "India",
    rating: 4.7,
    reviewsCount: 980,
    bestTime: "Nov - Feb",
    topAttractions: ["Alleppey Backwaters", "Munnar Tea Estates", "Hampi Ruins", "Meenakshi Temple"],
    vibe: "Tranquil & Cultural"
  },
  {
    id: "west-india",
    slug: "west-india",
    name: "West India",
    category: "india",
    subCategory: "Region",
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    description: "Vibrant deserts, bustling metropolises, sun-kissed beaches, and rich heritage.",
    region: "India",
    rating: 4.6,
    reviewsCount: 850,
    bestTime: "Oct - Mar",
    topAttractions: ["Rann of Kutch", "Mumbai Gateway", "Udaipur Palaces", "Goa Beaches"],
    vibe: "Vibrant & Diverse"
  },
  {
    id: "east-india",
    slug: "east-india",
    name: "East India",
    category: "india",
    subCategory: "Region",
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80",
    description: "Colonial charm, tea valleys, mangrove deltas, and deep-rooted artistic heritage.",
    region: "India",
    rating: 4.5,
    reviewsCount: 620,
    bestTime: "Oct - Mar",
    topAttractions: ["Darjeeling Tea Gardens", "Sundarbans National Park", "Puri Jagannath Temple", "Victoria Memorial"],
    vibe: "Artistic & Scenic"
  },
  {
    id: "north-east",
    slug: "north-east",
    name: "North East",
    category: "india",
    subCategory: "Region",
    image: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=800&q=80",
    description: "Unexplored hills, living root bridges, pristine waterfalls, and rich tribal traditions.",
    region: "India",
    rating: 4.9,
    reviewsCount: 740,
    bestTime: "Oct - Apr",
    topAttractions: ["Cherrapunji Waterfalls", "Kaziranga Rhino Park", "Tawang Monastery", "Loktak Lake"],
    vibe: "Mystical & Untouched",
    featured: true
  },
  {
    id: "hill-stations",
    slug: "hill-stations",
    name: "Hill Stations",
    category: "india",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=800&q=80",
    description: "Refreshing mountain air, misty pine forests, and breathtaking valleys.",
    region: "India",
    rating: 4.8,
    reviewsCount: 1100,
    bestTime: "Mar - Jun & Oct - Feb",
    topAttractions: ["Manali & Shimla", "Ooty & Kodaikanal", "Munnar", "Darjeeling"],
    vibe: "Refreshing & Romantic"
  },
  {
    id: "beaches",
    slug: "beaches",
    name: "Beaches",
    category: "india",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    description: "Golden sands, azure ocean waves, water sports, and vibrant nightlife.",
    region: "India",
    rating: 4.7,
    reviewsCount: 1350,
    bestTime: "Nov - Mar",
    topAttractions: ["Palolem Beach Goa", "Radhanagar Beach Andaman", "Varkala Cliff Beach", "Gokarna"],
    vibe: "Tropical & Relaxing"
  },
  {
    id: "wildlife",
    slug: "wildlife",
    name: "Wildlife",
    category: "india",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80",
    description: "Thrilling tiger safaris, dense jungle trails, and rare flora and fauna.",
    region: "India",
    rating: 4.6,
    reviewsCount: 530,
    bestTime: "Oct - Jun",
    topAttractions: ["Jim Corbett", "Ranthambore Tiger Reserve", "Kaziranga Park", "Gir Forest"],
    vibe: "Adventurous & Wild"
  },
  {
    id: "spiritual",
    slug: "spiritual",
    name: "Spiritual",
    category: "india",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    description: "Sacred rivers, ancient chanting, holy temples, and soul-elevating pilgrimages.",
    region: "India",
    rating: 4.8,
    reviewsCount: 890,
    bestTime: "All Year",
    topAttractions: ["Varanasi Ganga Aarti", "Rishikesh Yoga Centers", "Golden Temple", "Kedarnath & Badrinath"],
    vibe: "Sacred & Peaceful"
  },
  {
    id: "weekend-trips",
    slug: "weekend-trips",
    name: "Weekend Trips",
    category: "india",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    description: "Quick escapes to scenic getaways near major metro cities for a refreshing break.",
    region: "India",
    rating: 4.5,
    reviewsCount: 670,
    bestTime: "All Year",
    topAttractions: ["Lonavala & Khandala", "Coorg", "Jaipur", "Mussoorie"],
    vibe: "Quick & Rejuvenating"
  },

  // ── INTERNATIONAL ─────────────────────────────────
  {
    id: "europe",
    slug: "europe",
    name: "Europe",
    category: "international",
    subCategory: "Continent",
    image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80",
    description: "Fairy-tale castles, historical capital cities, culinary delights, and Alpine peaks.",
    region: "Global",
    rating: 4.9,
    reviewsCount: 2400,
    bestTime: "May - Sep",
    topAttractions: ["Eiffel Tower Paris", "Rome Colosseum", "Swiss Alps", "Santorini Sunset"],
    vibe: "Classic & Enchanting",
    featured: true
  },
  {
    id: "asia",
    slug: "asia",
    name: "Asia",
    category: "international",
    subCategory: "Continent",
    image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
    description: "Futuristic skyscrapers, tranquil shrines, pristine tropical islands, and street food.",
    region: "Global",
    rating: 4.8,
    reviewsCount: 1950,
    bestTime: "Oct - Apr",
    topAttractions: ["Tokyo Shibuya", "Bangkok Temples", "Singapore Marina Bay", "Bali Rice Terraces"],
    vibe: "Exotic & Dynamic"
  },
  {
    id: "middle-east",
    slug: "middle-east",
    name: "Middle East",
    category: "international",
    subCategory: "Region",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    description: "Ultra-modern mega towers, golden sand dunes, luxury shopping, and ancient history.",
    region: "Global",
    rating: 4.7,
    reviewsCount: 1600,
    bestTime: "Nov - Mar",
    topAttractions: ["Burj Khalifa", "Petra Jordan", "Sheikh Zayed Mosque", "Desert Safari"],
    vibe: "Luxurious & Historic"
  },
  {
    id: "africa",
    slug: "africa",
    name: "Africa",
    category: "international",
    subCategory: "Continent",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    description: "Untamed savannahs, Great Migration safaris, Pyramids of Giza, and Table Mountain.",
    region: "Global",
    rating: 4.8,
    reviewsCount: 820,
    bestTime: "Jul - Oct",
    topAttractions: ["Serengeti National Park", "Pyramids of Egypt", "Cape Town", "Victoria Falls"],
    vibe: "Breathtaking & Wild"
  },
  {
    id: "australia",
    slug: "australia",
    name: "Australia",
    category: "international",
    subCategory: "Country",
    image: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=800&q=80",
    description: "Iconic Opera House, Great Barrier Reef coral reefs, coastal road trips, and wildlife.",
    region: "Global",
    rating: 4.8,
    reviewsCount: 1120,
    bestTime: "Sep - Nov & Feb - Apr",
    topAttractions: ["Sydney Opera House", "Great Barrier Reef", "Gold Coast", "Uluru"],
    vibe: "Sunny & Outdoor"
  },
  {
    id: "north-america",
    slug: "north-america",
    name: "North America",
    category: "international",
    subCategory: "Continent",
    image: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=800&q=80",
    description: "Metropolitan skylines, legendary national parks, canyonlands, and coastal drives.",
    region: "Global",
    rating: 4.7,
    reviewsCount: 1450,
    bestTime: "May - Oct",
    topAttractions: ["New York Times Square", "Grand Canyon", "Banff Canada", "Yellowstone"],
    vibe: "Grand & Iconic"
  },
  {
    id: "south-america",
    slug: "south-america",
    name: "South America",
    category: "international",
    subCategory: "Continent",
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=800&q=80",
    description: "Lost Inca cities, Amazon rainforest, vibrant carnivals, and dramatic Andes mountains.",
    region: "Global",
    rating: 4.8,
    reviewsCount: 710,
    bestTime: "May - Sep",
    topAttractions: ["Machu Picchu", "Christ the Redeemer", "Amazon Rainforest", "Iguazu Falls"],
    vibe: "Passionate & Ancient"
  },
  {
    id: "island-destinations",
    slug: "island-destinations",
    name: "Island Destinations",
    category: "international",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    description: "Overwater bungalows, crystal lagoon waters, coral reefs, and tropical paradise.",
    region: "Global",
    rating: 4.9,
    reviewsCount: 1890,
    bestTime: "Nov - Apr",
    topAttractions: ["Maldives Atolls", "Bora Bora", "Phuket & Krabi", "Seychelles"],
    vibe: "Paradise & Serene",
    featured: true
  },
  {
    id: "luxury-travel",
    slug: "luxury-travel",
    name: "Luxury Travel",
    category: "international",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
    description: "5-star private resorts, Michelin-star dining, helicopter tours, and bespoke experiences.",
    region: "Global",
    rating: 4.9,
    reviewsCount: 940,
    bestTime: "All Year",
    topAttractions: ["Monaco Riviera", "Dubai Penthouse Resorts", "Swiss Chalets", "Amalfi Coast Yachts"],
    vibe: "Opulent & Exclusive"
  },
  {
    id: "honeymoon",
    slug: "honeymoon",
    name: "Honeymoon",
    category: "international",
    subCategory: "Theme",
    image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=80",
    description: "Unforgettable romantic hideaways, candlelit beach dinners, and scenic landscapes.",
    region: "Global",
    rating: 4.9,
    reviewsCount: 2100,
    bestTime: "All Year",
    topAttractions: ["Santorini Greece", "Maldives", "Paris France", "Venice Italy"],
    vibe: "Romantic & Intimate"
  },

  // ── POPULAR DESTINATIONS ──────────────────────────
  {
    id: "dubai",
    slug: "dubai",
    name: "Dubai",
    category: "popular",
    subCategory: "UAE",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    description: "City of superlatives with futuristic skyscrapers, desert adventures, and world-class luxury.",
    region: "United Arab Emirates",
    rating: 4.8,
    reviewsCount: 3200,
    bestTime: "Nov - Mar",
    topAttractions: ["Burj Khalifa", "Dubai Mall & Fountain", "Palm Jumeirah", "Desert Safari"],
    vibe: "Futuristic & Luxurious",
    featured: true
  },
  {
    id: "bali",
    slug: "bali",
    name: "Bali",
    category: "popular",
    subCategory: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
    description: "Island of the Gods featuring lush terraced rice fields, sacred temples, and surf beaches.",
    region: "Indonesia",
    rating: 4.9,
    reviewsCount: 2950,
    bestTime: "Apr - Oct",
    topAttractions: ["Ubud Rice Terraces", "Uluwatu Temple Sunset", "Nusa Penida Island", "Seminyak Beach"],
    vibe: "Spiritual & Tropical",
    featured: true
  },
  {
    id: "switzerland",
    slug: "switzerland",
    name: "Switzerland",
    category: "popular",
    subCategory: "Europe",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80",
    description: "Picture-perfect alpine landscapes, crystal-clear lakes, scenic mountain trains, and chocolates.",
    region: "Europe",
    rating: 4.9,
    reviewsCount: 2150,
    bestTime: "Jun - Sep & Dec - Mar",
    topAttractions: ["Matterhorn Zermatt", "Jungfraujoch", "Lake Geneva", "Interlaken"],
    vibe: "Alpine & Scenic",
    featured: true
  },
  {
    id: "maldives",
    slug: "maldives",
    name: "Maldives",
    category: "popular",
    subCategory: "Asia",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    description: "Ultimate tropical sanctuary of turquoise lagoons, private island villas, and vibrant sea life.",
    region: "Indian Ocean",
    rating: 4.9,
    reviewsCount: 2600,
    bestTime: "Nov - Apr",
    topAttractions: ["Overwater Water Villas", "Banana Reef Snorkeling", "Glowing Beach Vaadhoo", "Male City"],
    vibe: "Idyllic & Serene",
    featured: true
  },
  {
    id: "goa",
    slug: "goa",
    name: "Goa",
    category: "popular",
    subCategory: "India",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    description: "India's beach capital blending Portuguese heritage, golden shores, and lively night markets.",
    region: "West India",
    rating: 4.7,
    reviewsCount: 3800,
    bestTime: "Nov - Feb",
    topAttractions: ["Baga & Calangute Beaches", "Dudhsagar Waterfalls", "Old Goa Churches", "Fort Aguada"],
    vibe: "Festive & Sun-kissed"
  },
  {
    id: "kerala",
    slug: "kerala",
    name: "Kerala",
    category: "popular",
    subCategory: "India",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    description: "God's Own Country with tranquil houseboat cruises, misty tea gardens, and Ayurvedic wellness.",
    region: "South India",
    rating: 4.8,
    reviewsCount: 3100,
    bestTime: "Oct - Mar",
    topAttractions: ["Alleppey Houseboats", "Munnar Hills", "Varkala Cliff", "Periyar Wildlife Sanctuary"],
    vibe: "Tranquil & Lush"
  },
  {
    id: "thailand",
    slug: "thailand",
    name: "Thailand",
    category: "popular",
    subCategory: "Asia",
    image: "https://images.unsplash.com/photo-1506665531195-3566af294817?auto=format&fit=crop&w=800&q=80",
    description: "Land of Smiles offering golden temples, mouthwatering street food, limestone islands, and night markets.",
    region: "Southeast Asia",
    rating: 4.8,
    reviewsCount: 3400,
    bestTime: "Nov - Apr",
    topAttractions: ["Phuket Phi Phi Islands", "Bangkok Grand Palace", "Chiang Mai Temples", "Krabi Beaches"],
    vibe: "Vibrant & Warm"
  },
  {
    id: "japan",
    slug: "japan",
    name: "Japan",
    category: "popular",
    subCategory: "Asia",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    description: "Fascinating contrast of ancient tradition and neon-lit futuristic innovation, cherry blossoms, and Mount Fuji.",
    region: "East Asia",
    rating: 4.9,
    reviewsCount: 2750,
    bestTime: "Mar - May & Oct - Nov",
    topAttractions: ["Mount Fuji", "Kyoto Fushimi Inari", "Tokyo Shibuya Crossing", "Osaka Dotonbori"],
    vibe: "Harmonious & Captivating"
  },
  {
    id: "singapore",
    slug: "singapore",
    name: "Singapore",
    category: "popular",
    subCategory: "Asia",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80",
    description: "Garden city in a metropolis with futuristic Supertrees, world-class airport, and multicultural cuisine.",
    region: "Southeast Asia",
    rating: 4.8,
    reviewsCount: 2300,
    bestTime: "All Year",
    topAttractions: ["Gardens by the Bay", "Marina Bay Sands", "Sentosa Island", "Jewel Changi"],
    vibe: "Futuristic & Green"
  },
  {
    id: "paris",
    slug: "paris",
    name: "Paris",
    category: "popular",
    subCategory: "Europe",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    description: "The City of Light known for art, fashion, gastronomy, romantic boulevards, and timeless architecture.",
    region: "France",
    rating: 4.9,
    reviewsCount: 3600,
    bestTime: "Apr - May & Sep - Oct",
    topAttractions: ["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Champs-Élysées"],
    vibe: "Romantic & Cultured"
  }
];

export function getDestinationBySlug(slug: string): DestinationItem | undefined {
  return DESTINATIONS_DATA.find((item) => item.slug.toLowerCase() === slug.toLowerCase());
}
