export type TravelCategory =
  | "Religious"
  | "Adventure"
  | "Nature"
  | "Beaches"
  | "Heritage"
  | "Food"
  | "Family"
  | "Luxury"
  | "Cultural"
  | "Shopping"
  | "Nightlife"
  | "Romantic";

export interface CityDataEntry {
  name: string;
  countryId: string;
  regionName: string;
  description: string;
  bestTime: string;
  categories: TravelCategory[];
  attractions: string[];
}

const CITY_DB: Record<string, CityDataEntry> = {
  "Dhaka": { name: "Dhaka", countryId: "050", regionName: "Dhaka Division", description: "Vibrant capital of Bangladesh, a city of contrasts where Mughal architecture meets bustling modern life.", bestTime: "Nov - Feb", categories: ["Heritage", "Food"], attractions: ["Lalbagh Fort", "Ahsan Manzil", "National Museum", "Sadarghat"] },
  "Chittagong": { name: "Chittagong", countryId: "050", regionName: "Chittagong Division", description: "Port city on the Bay of Bengal with rolling hills, tea gardens, and the stunning Cox's Bazar nearby.", bestTime: "Nov - Mar", categories: ["Nature", "Beaches"], attractions: ["Cox's Bazar", "Patenga Beach", "Battali Hills"] },

  "Ahmedabad": { name: "Ahmedabad", countryId: "356", regionName: "Gujarat", description: "India's first UNESCO Heritage City, blending ancient pols with modernist architecture and legendary street food.", bestTime: "Nov - Feb", categories: ["Heritage", "Food", "Religious"], attractions: ["Sabarmati Ashram", "Adalaj Stepwell", "Jama Masjid", "Kankaria Lake"] },
  "Surat": { name: "Surat", countryId: "356", regionName: "Gujarat", description: "Diamond capital of the world and textile hub, famous for its vibrant bazaars and Gujarati cuisine.", bestTime: "Nov - Feb", categories: ["Food", "Heritage"], attractions: ["Dutch Garden", "Surat Castle", "Dumas Beach"] },
  "Dwarka": { name: "Dwarka", countryId: "356", regionName: "Gujarat", description: "One of the four sacred Char Dham pilgrimage sites, believed to be the ancient kingdom of Lord Krishna.", bestTime: "Oct - Mar", categories: ["Religious", "Heritage", "Beaches"], attractions: ["Dwarkadhish Temple", "Bet Dwarka", "Nageshwar Jyotirlinga"] },
  "Jaipur": { name: "Jaipur", countryId: "356", regionName: "Rajasthan", description: "The Pink City of India, a jewel of Rajasthani royalty with majestic palaces, vibrant bazaars, and ancient forts.", bestTime: "Oct - Mar", categories: ["Heritage", "Food", "Luxury", "Family"], attractions: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"] },
  "Udaipur": { name: "Udaipur", countryId: "356", regionName: "Rajasthan", description: "City of Lakes and romantic white-marble palaces set against the Aravalli Hills.", bestTime: "Sep - Mar", categories: ["Heritage", "Luxury", "Nature"], attractions: ["Lake Pichola", "City Palace", "Jag Mandir", "Saheliyon-ki-Bari"] },
  "Jodhpur": { name: "Jodhpur", countryId: "356", regionName: "Rajasthan", description: "The Blue City, crowned by the imposing Mehrangarh Fort overlooking painted indigo houses.", bestTime: "Oct - Mar", categories: ["Heritage", "Adventure"], attractions: ["Mehrangarh Fort", "Umaid Bhawan Palace", "Clock Tower"] },
  "Jaisalmer": { name: "Jaisalmer", countryId: "356", regionName: "Rajasthan", description: "Golden fortress city rising from the Thar Desert, offering camel safaris and ancient havelis.", bestTime: "Oct - Mar", categories: ["Heritage", "Adventure"], attractions: ["Jaisalmer Fort", "Patwon Ki Haveli", "Sam Sand Dunes"] },
  "Mumbai": { name: "Mumbai", countryId: "356", regionName: "Maharashtra", description: "India's Maximum City, a dazzling metropolis of Bollywood dreams, colonial architecture, and legendary street food.", bestTime: "Nov - Feb", categories: ["Food", "Heritage", "Luxury", "Family"], attractions: ["Gateway of India", "Marine Drive", "Elephanta Caves", "Chhatrapati Shivaji Terminus"] },
  "Pune": { name: "Pune", countryId: "356", regionName: "Maharashtra", description: "Oxford of the East, a cultural hub blending Maratha heritage with modern IT dynamism.", bestTime: "Oct - Mar", categories: ["Heritage", "Food"], attractions: ["Shaniwar Wada", "Aga Khan Palace", "Sinhagad Fort"] },
  "Kochi": { name: "Kochi", countryId: "356", regionName: "Kerala", description: "Queen of the Arabian Sea, where Chinese fishing nets, Portuguese churches, and spice markets create a cultural mosaic.", bestTime: "Oct - Mar", categories: ["Heritage", "Food", "Beaches"], attractions: ["Fort Kochi", "Chinese Fishing Nets", "Mattancherry Palace"] },
  "Trivandrum": { name: "Trivandrum", countryId: "356", regionName: "Kerala", description: "Gateway to Kerala's backwaters and tropical beaches, with a rich heritage of temples and palaces.", bestTime: "Oct - Mar", categories: ["Beaches", "Religious", "Nature"], attractions: ["Kovalam Beach", "Padmanabhaswamy Temple", "Napier Museum"] },
  "Munnar": { name: "Munnar", countryId: "356", regionName: "Kerala", description: "Emerald hill station wrapped in endless tea plantations, misty peaks, and cool mountain air.", bestTime: "Sep - Mar", categories: ["Nature", "Adventure"], attractions: ["Tea Museum", "Eravikulam National Park", "Top Station"] },
  "Bangalore": { name: "Bangalore", countryId: "356", regionName: "Karnataka", description: "India's Silicon Valley, a garden city of craft breweries, tech startups, and vibrant nightlife.", bestTime: "Oct - Feb", categories: ["Food", "Nature"], attractions: ["Lalbagh Botanical Garden", "Cubbon Park", "Nandi Hills"] },
  "Goa": { name: "Goa", countryId: "356", regionName: "Karnataka", description: "India's beach paradise with Portuguese colonial charm, psychedelic sunsets, and legendary nightlife.", bestTime: "Nov - Mar", categories: ["Beaches", "Heritage", "Food", "Luxury"], attractions: ["Baga Beach", "Basilica of Bom Jesus", "Dudhsagar Falls"] },
  "Mysore": { name: "Mysore", countryId: "356", regionName: "Karnataka", description: "City of Palaces and silk, known for Dasara festivities and regal grandeur.", bestTime: "Oct - Mar", categories: ["Heritage", "Religious"], attractions: ["Mysore Palace", "Chamundi Hills", "Brindavan Gardens"] },
  "Chennai": { name: "Chennai", countryId: "356", regionName: "Tamil Nadu", description: "Gateway to South India, a cultural powerhouse of Carnatic music, Bharatanatyam dance, and spicy cuisine.", bestTime: "Nov - Feb", categories: ["Food", "Heritage", "Beaches"], attractions: ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George"] },
  "Madurai": { name: "Madurai", countryId: "356", regionName: "Tamil Nadu", description: "Temple City of India, home to the magnificent Meenakshi Amman Temple, alive for over 2,500 years.", bestTime: "Oct - Mar", categories: ["Religious", "Heritage"], attractions: ["Meenakshi Amman Temple", "Thirumalai Nayakkar Palace"] },
  "Ooty": { name: "Ooty", countryId: "356", regionName: "Tamil Nadu", description: "Queen of Hill Stations in the Nilgiris, with tea gardens, toy train, and misty mountain vistas.", bestTime: "Oct - Jun", categories: ["Nature", "Family"], attractions: ["Botanical Garden", "Ooty Lake", "Nilgiri Mountain Railway"] },
  "Kolkata": { name: "Kolkata", countryId: "356", regionName: "West Bengal", description: "City of Joy, India's cultural capital with colonial grandeur, intellectual legacy, and incredible street food.", bestTime: "Oct - Mar", categories: ["Food", "Heritage", "Cultural"], attractions: ["Victoria Memorial", "Howrah Bridge", "Indian Museum"] },
  "Darjeeling": { name: "Darjeeling", countryId: "356", regionName: "West Bengal", description: "Himalayan queen famed for tea estates, toy train, and breathtaking Kanchenjunga sunrise views.", bestTime: "Mar - May", categories: ["Nature", "Adventure"], attractions: ["Tiger Hill", "Batasia Loop", "Tea Gardens"] },
  "Agra": { name: "Agra", countryId: "356", regionName: "Uttar Pradesh", description: "Home to the Taj Mahal, the eternal monument to love and the crown jewel of Mughal architecture.", bestTime: "Oct - Mar", categories: ["Heritage", "Religious"], attractions: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri"] },
  "Varanasi": { name: "Varanasi", countryId: "356", regionName: "Uttar Pradesh", description: "One of the oldest living cities on Earth, where spirituality flows with the sacred Ganges.", bestTime: "Oct - Mar", categories: ["Religious", "Heritage", "Cultural"], attractions: ["Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sarnath"] },
  "Shimla": { name: "Shimla", countryId: "356", regionName: "Himachal Pradesh", description: "Former British summer capital, a charming hill station with colonial architecture and mountain views.", bestTime: "Mar - Jun", categories: ["Nature", "Heritage", "Family"], attractions: ["The Ridge", "Mall Road", "Jakhoo Temple"] },
  "Manali": { name: "Manali", countryId: "356", regionName: "Himachal Pradesh", description: "Adventure hub nestled in the Kullu Valley, offering skiing, trekking, and stunning Himalayan landscapes.", bestTime: "Mar - Jun", categories: ["Adventure", "Nature"], attractions: ["Solang Valley", "Hadimba Temple", "Rohtang Pass"] },
  "Rishikesh": { name: "Rishikesh", countryId: "356", regionName: "Uttarakhand", description: "Yoga Capital of the World, a spiritual haven on the Ganges surrounded by Himalayan foothills.", bestTime: "Sep - Nov", categories: ["Religious", "Adventure", "Nature"], attractions: ["Laxman Jhula", "Ram Jhula", "Beatles Ashram"] },
  "Srinagar": { name: "Srinagar", countryId: "356", regionName: "Jammu and Kashmir", description: "Paradise on Earth, where houseboats drift on Dal Lake beneath the Zabarwan Mountains.", bestTime: "Mar - Oct", categories: ["Nature", "Heritage", "Luxury"], attractions: ["Dal Lake", "Mughal Gardens", "Shankaracharya Temple"] },
  "Leh": { name: "Leh", countryId: "356", regionName: "Ladakh", description: "High-altitude desert kingdom of ancient monasteries, crystal lakes, and dramatic mountain passes.", bestTime: "Jun - Sep", categories: ["Adventure", "Nature", "Religious"], attractions: ["Pangong Lake", "Leh Palace", "Nubra Valley"] },
  "Amritsar": { name: "Amritsar", countryId: "356", regionName: "Punjab", description: "Spiritual heart of Sikhism, home to the breathtaking Golden Temple and moving Jallianwala Bagh.", bestTime: "Oct - Mar", categories: ["Religious", "Heritage", "Food"], attractions: ["Golden Temple", "Jallianwala Bagh", "Wagah Border"] },

  "Los Angeles": { name: "Los Angeles", countryId: "840", regionName: "California", description: "City of Angels, where Hollywood dreams meet sun-kissed beaches and endless urban sprawl.", bestTime: "Mar - Nov", categories: ["Beaches", "Luxury", "Food", "Family"], attractions: ["Hollywood Sign", "Santa Monica Pier", "Griffith Observatory", "Beverly Hills"] },
  "San Francisco": { name: "San Francisco", countryId: "840", regionName: "California", description: "Fog-kissed jewel of the Pacific, with the Golden Gate Bridge, cable cars, and Silicon Valley innovation.", bestTime: "Sep - Nov", categories: ["Food", "Heritage", "Family"], attractions: ["Golden Gate Bridge", "Alcatraz Island", "Fisherman's Wharf"] },
  "New York City": { name: "New York City", countryId: "840", regionName: "New York", description: "The city that never sleeps, a concrete jungle of iconic skylines, Broadway lights, and cultural fusion.", bestTime: "Apr - Jun", categories: ["Food", "Heritage", "Luxury", "Family"], attractions: ["Statue of Liberty", "Central Park", "Times Square", "Empire State Building"] },
  "Miami": { name: "Miami", countryId: "840", regionName: "Florida", description: "Tropical playground of art deco glamour, Latin culture, and turquoise Atlantic waters.", bestTime: "Dec - Apr", categories: ["Beaches", "Luxury", "Food", "Nightlife"], attractions: ["South Beach", "Art Deco Historic District", "Everglades"] },
  "Orlando": { name: "Orlando", countryId: "840", regionName: "Florida", description: "Theme park capital of the world, a family paradise of magic, imagination, and year-round sunshine.", bestTime: "Mar - May", categories: ["Family", "Adventure"], attractions: ["Walt Disney World", "Universal Studios", "Kennedy Space Center"] },
  "Las Vegas": { name: "Las Vegas", countryId: "840", regionName: "Nevada", description: "Entertainment capital of the world, a neon-lit oasis of casinos, shows, and desert spectacle.", bestTime: "Mar - May", categories: ["Luxury", "Food", "Adventure"], attractions: ["The Strip", "Fremont Street", "Grand Canyon nearby"] },
  "Honolulu": { name: "Honolulu", countryId: "840", regionName: "Hawaii", description: "Tropical paradise on Oahu, where Diamond Head meets Waikiki and Aloha spirit pervades everything.", bestTime: "Apr - Oct", categories: ["Beaches", "Nature", "Luxury"], attractions: ["Waikiki Beach", "Pearl Harbor", "Diamond Head"] },
  "Chicago": { name: "Chicago", countryId: "840", regionName: "Illinois", description: "Windy City of architectural marvels, deep-dish pizza, and vibrant blues and jazz heritage.", bestTime: "May - Oct", categories: ["Food", "Heritage", "Family"], attractions: ["Willis Tower", "Millennium Park", "Navy Pier"] },
  "Seattle": { name: "Seattle", countryId: "840", regionName: "Washington", description: "Emerald City of coffee culture, tech innovation, and stunning Puget Sound mountain views.", bestTime: "Jun - Sep", categories: ["Nature", "Food", "Adventure"], attractions: ["Space Needle", "Pike Place Market", "Mount Rainier"] },
  "Denver": { name: "Denver", countryId: "840", regionName: "Colorado", description: "Mile High City at the foot of the Rockies, blending outdoor adventure with craft beer culture.", bestTime: "May - Oct", categories: ["Adventure", "Nature"], attractions: ["Rocky Mountain National Park", "Red Rocks", "Union Station"] },
  "Nashville": { name: "Nashville", countryId: "840", regionName: "Tennessee", description: "Music City USA, the soulful heart of country music with legendary honky-tonks and hot chicken.", bestTime: "Mar - Nov", categories: ["Food", "Heritage", "Cultural"], attractions: ["Grand Ole Opry", "Broadway", "Country Music Hall of Fame"] },
  "New Orleans": { name: "New Orleans", countryId: "840", regionName: "Louisiana", description: "The Big Easy, a intoxicating blend of jazz, Creole cuisine, Mardi Gras spirit, and French Quarter charm.", bestTime: "Feb - May", categories: ["Food", "Heritage", "Cultural"], attractions: ["French Quarter", "Bourbon Street", "Garden District"] },
  "Boston": { name: "Boston", countryId: "840", regionName: "Massachusetts", description: "America's Walking City, rich in Revolutionary history, world-class universities, and coastal charm.", bestTime: "May - Oct", categories: ["Heritage", "Food", "Family"], attractions: ["Freedom Trail", "Fenway Park", "Cambridge"] },
  "Phoenix": { name: "Phoenix", countryId: "840", regionName: "Arizona", description: "Valley of the Sun, a desert metropolis surrounded by dramatic red rock landscapes and saguaro cacti.", bestTime: "Nov - Apr", categories: ["Nature", "Adventure"], attractions: ["Grand Canyon nearby", "Sedona", "Desert Botanical Garden"] },
  "Atlanta": { name: "Atlanta", countryId: "840", regionName: "Georgia", description: "Capital of the New South, where civil rights history meets Southern hospitality and peachy charm.", bestTime: "Mar - May", categories: ["Heritage", "Food"], attractions: ["Martin Luther King Jr. National Historic Site", "Georgia Aquarium", "World of Coca-Cola"] },

  "Tokyo": { name: "Tokyo", countryId: "392", regionName: "Tokyo", description: "Neon-lit futuristic metropolis where ancient temples sit alongside cutting-edge technology and anime culture.", bestTime: "Mar - May", categories: ["Food", "Heritage", "Luxury", "Family"], attractions: ["Shibuya Crossing", "Senso-ji Temple", "Mt. Fuji nearby", "Akihabara"] },
  "Osaka": { name: "Osaka", countryId: "392", regionName: "Osaka", description: "Japan's Kitchen, a foodie paradise of takoyaki, street eats, and vibrant nightlife.", bestTime: "Mar - May", categories: ["Food", "Family", "Heritage"], attractions: ["Osaka Castle", "Dotonbori", "Universal Studios Japan"] },
  "Kyoto": { name: "Kyoto", countryId: "392", regionName: "Kyoto", description: "Imperial capital of grace, where golden pavilions, bamboo groves, and geisha culture endure.", bestTime: "Mar - May", categories: ["Heritage", "Religious", "Nature"], attractions: ["Fushimi Inari Shrine", "Kinkaku-ji", "Arashiyama Bamboo Grove"] },
  "Hokkaido": { name: "Hokkaido", countryId: "392", regionName: "Hokkaido", description: "Japan's northern wilderness of powder snow, lavender fields, and volcanic hot springs.", bestTime: "Dec - Feb", categories: ["Nature", "Adventure", "Food"], attractions: ["Niseko Ski Resort", "Furano Lavender Fields", "Sapporo Snow Festival"] },
  "Bali": { name: "Bali", countryId: "360", regionName: "Bali", description: "Island of the Gods, an enchanting blend of emerald rice terraces, ancient temples, and tropical beaches.", bestTime: "Apr - Oct", categories: ["Beaches", "Religious", "Nature", "Luxury"], attractions: ["Ubud Rice Terraces", "Tanah Lot Temple", "Seminyak Beach", "Mount Batur"] },
  "Jakarta": { name: "Jakarta", countryId: "360", regionName: "Java", description: "Indonesia's sprawling capital, a melting pot of cultures, cuisines, and colonial history.", bestTime: "May - Oct", categories: ["Food", "Heritage"], attractions: ["Old Town", "National Monument", "Thousand Islands"] },
  "Yogyakarta": { name: "Yogyakarta", countryId: "360", regionName: "Java", description: "Cultural heart of Java, home to ancient Borobudur and Prambanan temples and royal traditions.", bestTime: "May - Oct", categories: ["Heritage", "Religious", "Adventure"], attractions: ["Borobudur Temple", "Prambanan Temple", "Sultan's Palace"] },

  "London": { name: "London", countryId: "826", regionName: "England", description: "Global city of centuries-old royalty, cutting-edge culture, and an endlessly diverse food scene.", bestTime: "May - Sep", categories: ["Heritage", "Food", "Luxury", "Family"], attractions: ["Big Ben", "Tower of London", "British Museum", "Buckingham Palace"] },
  "Edinburgh": { name: "Edinburgh", countryId: "826", regionName: "Scotland", description: "Auld Reekie's dramatic skyline of castles, cobblestones, and festivals against a volcanic rock.", bestTime: "May - Sep", categories: ["Heritage", "Food", "Adventure"], attractions: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat"] },
  "Paris": { name: "Paris", countryId: "250", regionName: "Ile-de-France", description: "City of Light, the world's most romantic capital of art, fashion, wine, and timeless elegance.", bestTime: "Apr - Jun", categories: ["Food", "Heritage", "Luxury", "Romantic"], attractions: ["Eiffel Tower", "Louvre Museum", "Notre-Dame", "Montmartre"] },
  "Nice": { name: "Nice", countryId: "250", regionName: "Provence-Alpes-Cote d'Azur", description: "Jewel of the French Riviera, where azure Mediterranean waters meet pastel-colored old town charm.", bestTime: "May - Oct", categories: ["Beaches", "Food", "Luxury"], attractions: ["Promenade des Anglais", "Vieux Nice", "Matisse Museum"] },
  "Munich": { name: "Munich", countryId: "276", regionName: "Bavaria", description: "Capital of beer gardens and Bavarian tradition, with BMW precision and fairy-tale castle day trips.", bestTime: "May - Oct", categories: ["Food", "Heritage", "Family"], attractions: ["Marienplatz", "English Garden", "Neuschwanstein Castle nearby"] },
  "Berlin": { name: "Berlin", countryId: "276", regionName: "Berlin", description: "Germany's gritty creative capital, where Cold War history collides with vibrant art and nightlife.", bestTime: "May - Sep", categories: ["Heritage", "Cultural", "Food"], attractions: ["Brandenburg Gate", "Berlin Wall Memorial", "Museum Island"] },
  "Rome": { name: "Rome", countryId: "380", regionName: "Lazio", description: "Eternal City of ancient empires, where the Colosseum, Vatican, and pasta create living history.", bestTime: "Apr - Jun", categories: ["Heritage", "Food", "Religious", "Family"], attractions: ["Colosseum", "Vatican City", "Trevi Fountain", "Pantheon"] },
  "Venice": { name: "Venice", countryId: "380", regionName: "Veneto", description: "Floating City of canals, gondolas, and Renaissance splendor rising from the Adriatic lagoon.", bestTime: "Apr - Jun", categories: ["Heritage", "Food", "Romantic"], attractions: ["St. Mark's Basilica", "Rialto Bridge", "Doge's Palace"] },
  "Florence": { name: "Florence", countryId: "380", regionName: "Tuscany", description: "Cradle of the Renaissance, where Michelangelo's David and Brunelleschi's dome define beauty.", bestTime: "Apr - Jun", categories: ["Heritage", "Food", "Luxury"], attractions: ["Uffizi Gallery", "Duomo", "Ponte Vecchio", "Accademia"] },
  "Barcelona": { name: "Barcelona", countryId: "724", regionName: "Catalonia", description: "Gaudi's dream city, where modernist architecture, Gothic lanes, and Mediterranean beaches unite.", bestTime: "May - Jun", categories: ["Beaches", "Food", "Heritage", "Family"], attractions: ["Sagrada Familia", "Park Guell", "Las Ramblas", "Gothic Quarter"] },
  "Madrid": { name: "Madrid", countryId: "724", regionName: "Madrid", description: "Spain's elegant capital of world-class museums, tapas culture, and晚night-time paseo tradition.", bestTime: "Mar - Jun", categories: ["Food", "Heritage", "Cultural"], attractions: ["Prado Museum", "Royal Palace", "Retiro Park", "Puerta del Sol"] },
  "Istanbul": { name: "Istanbul", countryId: "792", regionName: "Istanbul", description: "City on Two Continents, where Byzantine domes, Ottoman bazaars, and Turkish cuisine mesmerize.", bestTime: "Apr - May", categories: ["Heritage", "Food", "Religious", "Shopping"], attractions: ["Hagia Sophia", "Grand Bazaar", "Blue Mosque", "Bosphorus Cruise"] },
  "Cappadocia": { name: "Cappadocia", countryId: "792", regionName: "Cappadocia", description: "Surreal lunar landscape of fairy chimneys and cave hotels, best explored by hot air balloon at dawn.", bestTime: "Apr - Oct", categories: ["Adventure", "Nature", "Heritage"], attractions: ["Hot Air Balloon Rides", "Goreme Open-Air Museum", "Underground Cities"] },
  "Dubai": { name: "Dubai", countryId: "784", regionName: "Dubai", description: "Futuristic city of superlatives, where the world's tallest tower meets desert safari adventures.", bestTime: "Nov - Mar", categories: ["Luxury", "Adventure", "Family", "Shopping"], attractions: ["Burj Khalifa", "Palm Jumeirah", "Desert Safari", "Dubai Mall"] },
  "Cairo": { name: "Cairo", countryId: "818", regionName: "Cairo", description: "City of a Thousand Minarets, gateway to the pyramids and the mighty Nile.", bestTime: "Oct - Apr", categories: ["Heritage", "Adventure", "Food"], attractions: ["Great Pyramids of Giza", "Egyptian Museum", "Khan El-Khalili"] },
  "Marrakech": { name: "Marrakech", countryId: "504", regionName: "Marrakech-Safi", description: "Red City of sensory overload, with labyrinthine souks, riads, and the Jemaa el-Fnaa square.", bestTime: "Mar - May", categories: ["Heritage", "Food", "Shopping", "Luxury"], attractions: ["Jemaa el-Fnaa", "Majorelle Garden", "Bahia Palace"] },
  "Cape Town": { name: "Cape Town", countryId: "710", regionName: "Western Cape", description: "Mother City nestled beneath Table Mountain, where African, Dutch, and Malay cultures converge.", bestTime: "Nov - Mar", categories: ["Nature", "Adventure", "Food", "Beaches"], attractions: ["Table Mountain", "Cape of Good Hope", "Robben Island", "V&A Waterfront"] },
  "Bangkok": { name: "Bangkok", countryId: "764", regionName: "Bangkok", description: "City of Angels, an intoxicating swirl of golden temples, tuk-tuks, floating markets, and street food.", bestTime: "Nov - Feb", categories: ["Food", "Religious", "Shopping", "Heritage"], attractions: ["Grand Palace", "Wat Arun", "Chatuchak Market", "Khao San Road"] },
  "Chiang Mai": { name: "Chiang Mai", countryId: "764", regionName: "Chiang Mai", description: "Rose of the North, a tranquil temple city surrounded by mountains and night bazaar charm.", bestTime: "Nov - Feb", categories: ["Religious", "Food", "Nature", "Adventure"], attractions: ["Doi Suthep Temple", "Night Bazaar", "Elephant Sanctuaries"] },
  "Phuket": { name: "Phuket", countryId: "764", regionName: "Phuket", description: "Thailand's largest island, a tropical playground of turquoise waters, limestone karsts, and nightlife.", bestTime: "Nov - Apr", categories: ["Beaches", "Adventure", "Luxury"], attractions: ["Patong Beach", "Phi Phi Islands", "Big Buddha"] },
  "Hanoi": { name: "Hanoi", countryId: "704", regionName: "Red River Delta", description: "Vietnam's ancient capital, where French colonial charm, Hoan Kiem Lake, and pho create timeless allure.", bestTime: "Oct - Dec", categories: ["Food", "Heritage", "Cultural"], attractions: ["Old Quarter", "Hoan Kiem Lake", "Ho Chi Minh Mausoleum"] },
  "Singapore": { name: "Singapore", countryId: "702", regionName: "Central", description: "Garden City of futuristic skyline, hawker food perfection, and lush tropical greenery.", bestTime: "Year-round", categories: ["Food", "Family", "Luxury", "Nature"], attractions: ["Marina Bay Sands", "Gardens by the Bay", "Sentosa Island"] },
  "Seoul": { name: "Seoul", countryId: "410", regionName: "Seoul", description: "Dynamic capital of K-culture, where ancient palaces coexist with K-pop, skincare, and LED-lit streets.", bestTime: "Mar - May", categories: ["Food", "Heritage", "Shopping", "Cultural"], attractions: ["Gyeongbokgung Palace", "Myeongdong", "N Seoul Tower", "Bukchon Hanok Village"] },
  "Kathmandu": { name: "Kathmandu", countryId: "524", regionName: "Bagmati", description: "Roof of the World's gateway city, a spiritual tapestry of stupas, temples, and Himalayan ambition.", bestTime: "Oct - Mar", categories: ["Religious", "Adventure", "Heritage"], attractions: ["Boudhanath Stupa", "Pashupatinath Temple", "Durbar Square"] },
  "Sydney": { name: "Sydney", countryId: "036", regionName: "New South Wales", description: "Harbour City where the Opera House sails and Harbour Bridge frame sun-drenched coastal lifestyle.", bestTime: "Sep - Nov", categories: ["Beaches", "Food", "Family", "Heritage"], attractions: ["Sydney Opera House", "Bondi Beach", "Harbour Bridge"] },
  "Queenstown": { name: "Queenstown", countryId: "554", regionName: "Otago", description: "Adventure Capital of the World, set among dramatic Southern Alps and crystal-clear lakes.", bestTime: "Jun - Oct", categories: ["Adventure", "Nature", "Luxury"], attractions: ["Milford Sound", "Bungee Jumping", "Skyline Gondola"] },
  "Reykjavik": { name: "Reykjavik", countryId: "352", regionName: "Capital Region", description: "World's most northerly capital, gateway to geysers, glaciers, northern lights, and volcanic wonders.", bestTime: "Sep - Mar", categories: ["Nature", "Adventure"], attractions: ["Blue Lagoon", "Golden Circle", "Northern Lights"] },
  "Athens": { name: "Athens", countryId: "300", regionName: "Attica", description: "Cradle of Western civilization, where the Parthenon crowns a city reborn with vibrant urban energy.", bestTime: "Apr - Jun", categories: ["Heritage", "Food", "Cultural"], attractions: ["Acropolis", "Plaka", "Ancient Agora"] },
  "Santorini": { name: "Santorini", countryId: "300", regionName: "South Aegean", description: "Volcanic island of whitewashed villages, blue domes, and legendary Aegean sunsets.", bestTime: "May - Oct", categories: ["Beaches", "Luxury", "Romantic"], attractions: ["Oia Sunset", "Red Beach", "Akrotiri Ruins"] },
  "Amsterdam": { name: "Amsterdam", countryId: "528", regionName: "North Holland", description: "Venice of the North, a canal-laced city of bicycles, masterpieces, and liberal charm.", bestTime: "Apr - Sep", categories: ["Heritage", "Food", "Cultural"], attractions: ["Rijksmuseum", "Anne Frank House", "Canal Cruise"] },
  "Vienna": { name: "Vienna", countryId: "040", regionName: "Vienna", description: "Imperial City of music, coffeehouses, and Baroque grandeur along the Danube.", bestTime: "Apr - Oct", categories: ["Heritage", "Food", "Cultural", "Luxury"], attractions: ["Schonbrunn Palace", "St. Stephen's Cathedral", "Belvedere"] },
  "Prague": { name: "Prague", countryId: "203", regionName: "Prague", description: "City of a Hundred Spires, a fairy-tale labyrinth of Gothic towers, craft beer, and old-world charm.", bestTime: "May - Sep", categories: ["Heritage", "Food", "Cultural"], attractions: ["Charles Bridge", "Old Town Square", "Prague Castle"] },
  "Lisbon": { name: "Lisbon", countryId: "620", regionName: "Lisbon", description: "City of Seven Hills, where fado echoes through pastel alleyways and pastel de nata melts perfectly.", bestTime: "Mar - Oct", categories: ["Food", "Heritage", "Beaches"], attractions: ["Belem Tower", "Alfama", "Tram 28"] },
  "Zurich": { name: "Zurich", countryId: "756", regionName: "Zurich", description: "Swiss perfection of alpine lakeside elegance, chocolate, watches, and pristine Old Town.", bestTime: "Jun - Sep", categories: ["Nature", "Luxury", "Heritage"], attractions: ["Lake Zurich", "Old Town", "Bahnhofstrasse"] },
  "Dubrovnik": { name: "Dubrovnik", countryId: "191", regionName: "Dubrovnik-Neretva", description: "Pearl of the Adriatic, a walled medieval city of terracotta roofs and crystal Adriatic waters.", bestTime: "May - Sep", categories: ["Heritage", "Beaches", "Luxury"], attractions: ["City Walls", "Stradun", "Lokrum Island"] },
  "Lima": { name: "Lima", countryId: "604", regionName: "Lima", description: "Gastronomic capital of South America, where Pacific cliffs meet colonial architecture and ceviche perfection.", bestTime: "Dec - Apr", categories: ["Food", "Heritage"], attractions: ["Miraflores", "Historic Centre", "Barranco"] },
  "Rio de Janeiro": { name: "Rio de Janeiro", countryId: "076", regionName: "Rio de Janeiro", description: "Marvellous City of carnival rhythms, Sugarloaf peaks, Copacabana beach, and Carioca joy.", bestTime: "May - Oct", categories: ["Beaches", "Adventure", "Food", "Cultural"], attractions: ["Christ the Redeemer", "Sugarloaf Mountain", "Copacabana Beach"] },
  "Buenos Aires": { name: "Buenos Aires", countryId: "032", regionName: "Buenos Aires", description: "Paris of South America, where tango echoes through La Boca and steak is an art form.", bestTime: "Mar - May", categories: ["Food", "Cultural", "Heritage"], attractions: ["La Boca", "Recoleta Cemetery", "Teatro Colon"] },
  "Cusco": { name: "Cusco", countryId: "604", regionName: "Cusco", description: "Navel of the World, Incan imperial capital and gateway to Machu Picchu in the Andes.", bestTime: "May - Sep", categories: ["Heritage", "Adventure", "Religious"], attractions: ["Machu Picchu", "Sacred Valley", "Plaza de Armas"] },
  "Petra": { name: "Amman", countryId: "400", regionName: "Amman", description: "White Rose City of the desert, Jordan's capital blending ancient ruins with modern Middle Eastern culture.", bestTime: "Mar - May", categories: ["Heritage", "Adventure", "Food"], attractions: ["Petra", "Amman Citadel", "Dead Sea nearby"] },
  "Havana": { name: "Havana", countryId: "192", regionName: "Artemisa", description: "Time-capsule city of vintage convertibles, salsa rhythms, and faded colonial grandeur.", bestTime: "Nov - Apr", categories: ["Heritage", "Cultural", "Beaches"], attractions: ["Old Havana", "Malecon", "El Capitolio"] },
  "Lhasa": { name: "Lhasa", countryId: "156", regionName: "Tibet", description: "Forbidden City on the Roof of the World, a mystical Buddhist capital at 3,650 meters altitude.", bestTime: "May - Oct", categories: ["Religious", "Adventure", "Heritage"], attractions: ["Potala Palace", "Jokhang Temple", "Barkhor Street"] },
  "Hong Kong": { name: "Hong Kong", countryId: "156", regionName: "Guangdong", description: "Pearl of the Orient, a vertical city of neon-lit markets, dim sum, and dramatic harbor skyline.", bestTime: "Oct - Dec", categories: ["Food", "Shopping", "Heritage"], attractions: ["Victoria Peak", "Star Ferry", "Temple Street Night Market"] },
};

export function getCityData(cityName: string, countryId?: string): CityDataEntry | null {
  const entry = CITY_DB[cityName];
  if (!entry) return null;
  if (countryId && entry.countryId !== countryId) return null;
  return entry;
}

export function getAllCityNames(): string[] {
  return Object.keys(CITY_DB);
}

export const TRAVEL_CATEGORIES: TravelCategory[] = [
  "Religious", "Adventure", "Nature", "Beaches",
  "Heritage", "Food", "Family", "Luxury",
];

export const CATEGORY_ICONS: Record<TravelCategory, string> = {
  Religious: "M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5",
  Adventure: "M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064",
  Nature: "M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z",
  Beaches: "M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z",
  Heritage: "M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4",
  Food: "M21 15.546c-.523 0-1.046.151-1.5.454a2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0A2.704 2.704 0 003 15.546",
  Family: "M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z",
  Luxury: "M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z",
  Cultural: "M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253",
  Shopping: "M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z",
  Nightlife: "M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z",
  Romantic: "M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z",
};

export function searchCityData(query: string): CityDataEntry[] {
  const q = query.toLowerCase();
  return Object.values(CITY_DB).filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.categories.some((cat) => cat.toLowerCase().includes(q)),
  );
}
